### ISSUE TITLE
How to set the max line length parameter?

### ISSUE THREAD

**Issue by favorart** [ankitvgupta/pycodestyle-action#11]
````
      - name: pycodestyle
        uses: ankitvgupta/pycodestyle-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRECOMMAND_MESSAGE: You have style errors. See them below.
        with:
````
**`              arguments: '--max-line-length=120'`**
